Repository cusma/d-asa, pull requests merged in 2025-02, with the labels that each got.

#26 refactor: updating to latest betas reflecting latest feedback
  poetry.lock
  pyproject.toml
  smart_contracts/__main__.py
  smart_contracts/_helpers/__init__.py
  smart_contracts/_helpers/build.py
  smart_contracts/_helpers/config.py
  smart_contracts/_helpers/deploy.py
Labels: dependencies, python

#27 fix: algokit utils deployment
  poetry.lock
  pyproject.toml
Labels: bug, dependencies, python

#28 chore: dependabot workflow
  .github/dependabot.yml
  poetry.lock
  pyproject.toml
  smart_contracts/__main__.py
  tests/base_d_asa/conftest.py
  tests/fixed_coupon_bond/conftest.py
  tests/perpetual_bond/conftest.py
  tests/zero_coupon_bond/conftest.py
Labels: dependencies, python

#29 release: v0.4.0
  docs/contributors.md
  pyproject.toml
Labels: release
